/* #undef ITALC_BUILD_LINUX */
#define ITALC_BUILD_WIN32 1
/* #undef ITALC_BUILD_APPLE */

#define ITALC_HOST_X86 1
/* #undef ITALC_HOST_X86_64 */

/* #undef ITALC_HAVE_ARPA_INET_H */
#define ITALC_HAVE_FCNTL_H 1
#define ITALC_HAVE_LIMITS_H 1
#define ITALC_HAVE_MEMORY_H 1
/* #undef ITALC_HAVE_NETDB_H */
/* #undef ITALC_HAVE_NETINET_IN_H */
#define ITALC_HAVE_STDINT_H 1
#define ITALC_HAVE_STDLIB_H 1
#define ITALC_HAVE_STDBOOL_H 1
#define ITALC_HAVE_STRING_H 1
#define ITALC_HAVE_STRINGS_H 1
/* #undef ITALC_HAVE_SYS_IOCTL_H */
/* #undef ITALC_HAVE_SYS_SOCKET_H */
#define ITALC_HAVE_SYS_TIME_H 1
#define ITALC_HAVE_SYS_TIMEB_H 1
#define ITALC_HAVE_SYS_STAT_H 1
/* #undef ITALC_HAVE_SYSLOG_H */
#define ITALC_HAVE_UNISTD_H 1
/* #undef ITALC_HAVE_PWD_H */
#define ITALC_HAVE_SYS_TYPES_H 1
/* #undef ITALC_HAVE_UTMPX_H */
/* #undef ITALC_HAVE_SYS_WAIT_H */
#define ITALC_HAVE_TIME_H 1
#define ITALC_HAVE_ERRNO_H 1
#define ITALC_HAVE_PTHREAD_H 1
/* #undef ITALC_HAVE_SYS_IPC_H */
/* #undef ITALC_HAVE_SYS_SHM_H */
#define ITALC_HAVE_STDARG_H 1
#define ITALC_HAVE_SIGNAL_H 1
#define ITALC_HAVE_CTYPE_H 1
#define ITALC_HAVE_PROCESS_H 1
/* #undef ITALC_HAVE_DLFCN_H */
#define ITALC_HAVE_INTTYPES_H 1
/* #undef ITALC_HAVE_VFORK_H */
/* #undef ITALC_HAVE_LINUX_FB_H */
/* #undef ITALC_HAVE_LINUX_INPUT_H */
/* #undef ITALC_HAVE_LINUX_UINPUT_H */
/* #undef ITALC_HAVE_LINUX_VIDEODEV_H */


#define ITALC_HAVE_FTIME 1
/* #undef ITALC_HAVE_MKFIFO */
#define ITALC_HAVE_DUP2 1
#define ITALC_HAVE_FLOOR 1
/* #undef ITALC_HAVE_GETHOSTBYNAME */
/* #undef ITALC_HAVE_GETHOSTNAME */
#define ITALC_HAVE_GETTIMEOFDAY 1
/* #undef ITALC_HAVE_INET_NTOA */
#define ITALC_HAVE_MEMCMP 1
#define ITALC_HAVE_MEMMOVE 1
#define ITALC_HAVE_MEMCPY 1
#define ITALC_HAVE_MEMSET 1
/* #undef ITALC_HAVE_MMAP */
#define ITALC_HAVE_POW 1
#define ITALC_HAVE_PUTENV 1
/* #undef ITALC_HAVE_SELECT */
/* #undef ITALC_HAVE_SOCKET */
#define ITALC_HAVE_STRCHR 1
#define ITALC_HAVE_STRDUP 1
#define ITALC_HAVE_STRERROR 1
#define ITALC_HAVE_STRPBRK 1
#define ITALC_HAVE_STRRCHR 1
#define ITALC_HAVE_STRSTR 1
/* #undef ITALC_HAVE_UNAME */
/* #undef ITALC_HAVE_SETSID */
/* #undef ITALC_HAVE_GETPWUID */
/* #undef ITALC_HAVE_GETPWNAM */
/* #undef ITALC_HAVE_GETUID */
/* #undef ITALC_HAVE_GETEUID */
/* #undef ITALC_HAVE_WAITPID */
/* #undef ITALC_HAVE_SETUTXENT */
/* #undef ITALC_HAVE_SETPGRP */
/* #undef ITALC_HAVE_SETEUID */
/* #undef ITALC_HAVE_GRANTPT */
/* #undef ITALC_HAVE_GETSPNAM */
/* #undef ITALC_HAVE_INITGROUPS */


/* x11vnc configuration */
#define ITALC_ALLOW24BPP
#define ITALC_BACKCHANNEL
/* #undef ITALC_HAVE_X11 */
/* #undef ITALC_HAVE_XSHM */
/* #undef ITALC_HAVE_XTEST */
/* #undef ITALC_HAVE_LIBXINERAMA */
/* #undef ITALC_HAVE_LIBXRANDR */
/* #undef ITALC_HAVE_LIBXFIXES */
/* #undef ITALC_HAVE_LIBXDAMAGE */
/* #undef ITALC_HAVE_SOLARIS_XREADSCREEN */
/* #undef ITALC_HAVE_FBPM */
/* #undef ITALC_HAVE_DPMS */
/* #undef ITALC_HAVE_XTESTGRABCONTROL */
/* #undef ITALC_HAVE_RECORD */
/* #undef ITALC_HAVE_IRIX_XREADDISPLAY */
/* #undef ITALC_HAVE_XKBLIB_H */
/* #undef ITALC_HAVE_XKEYBOARD */
/* #undef ITALC_HAVE_LIBCRYPT */
#define ITALC_HAVE_LIBPTHREAD 1
#define ITALC_HAVE_TLS 1
